"""
Security Audit Report Generator
CodeAlpha Security Audit Task 3: Secure Coding Review & Vulnerability Analysis
"""

import json
from datetime import datetime
from typing import Dict, Any

class ReportGenerator:
    """Generates comprehensive Security Review Reports in Markdown, HTML, and JSON formats."""

    @staticmethod
    def generate_markdown(analysis_results: Dict[str, Any], project_name: str = "CodeAlpha Secure Coding Review") -> str:
        metrics = analysis_results.get("metrics", {})
        findings = analysis_results.get("findings", [])
        bandit = analysis_results.get("bandit", {})
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

        md = []
        md.append(f"# 🛡️ Security Coding Review & Audit Report")
        md.append(f"**Project Name:** {project_name}")
        md.append(f"**Analysis Timestamp:** {timestamp}")
        md.append(f"**File Analyzed:** `{metrics.get('filename', 'submitted_code.py')}`")
        md.append(f"**Lines of Code Analyzed:** {metrics.get('lines_analyzed', 0)}")
        md.append(f"**Analysis Engine:** Python AST & Rule-based Static Security Analyzer")
        md.append(f"**Bandit AST Integration Status:** {bandit.get('status', 'Built-in static analysis active.')}")
        md.append("\n---\n")

        md.append("## 📊 Executive Summary & Metrics")
        md.append("| Metric | Count |")
        md.append("| :--- | :--- |")
        md.append(f"| **Total Security Findings** | `{metrics.get('total_findings', 0)}` |")
        md.append(f"| 🔴 **Critical Severity** | `{metrics.get('critical_count', 0)}` |")
        md.append(f"| 🟠 **High Severity** | `{metrics.get('high_count', 0)}` |")
        md.append(f"| 🟡 **Medium Severity** | `{metrics.get('medium_count', 0)}` |")
        md.append(f"| 🔵 **Low Severity** | `{metrics.get('low_count', 0)}` |")
        md.append(f"| ⚪ **Info Severity** | `{metrics.get('info_count', 0)}` |")
        md.append("\n---\n")

        md.append("## 🐛 Vulnerability Findings & Remediation Catalog")
        if not findings:
            md.append("✅ **No potential security vulnerabilities detected during static code review.**\n")
        else:
            for idx, f in enumerate(findings, 1):
                sev_icon = {
                    "CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪"
                }.get(f["severity"], "⚠️")

                md.append(f"### {idx}. [{f['finding_id']}] {f['category']}")
                md.append(f"- **Severity:** {sev_icon} `{f['severity']}` | **Confidence:** `{f['confidence']}` | **CWE:** `{f.get('cwe', 'N/A')}`")
                md.append(f"- **Location:** Line {f['line_number']}")
                md.append(f"- **Vulnerable Snippet:**")
                md.append(f"```python\n{f['code_snippet']}\n```")
                md.append(f"- **Explanation:** {f['explanation']}")
                md.append(f"- **Security Impact:** {f['security_impact']}")
                md.append(f"- **Recommended Remediation:** {f['remediation']}")
                md.append(f"- **Verification Step:** {f['verification']}")
                if f.get("secure_example"):
                    md.append(f"- **Secure Code Example:**")
                    md.append(f"```python\n{f['secure_example']}\n```")
                md.append("\n")

        if bandit.get("available") and bandit.get("results"):
            md.append("\n---\n")
            md.append("## 🤖 Bandit AST Static Analyzer Findings")
            for b_idx, b_item in enumerate(bandit.get("results", []), 1):
                md.append(f"#### B-{b_idx}. {b_item.get('test_name')} ({b_item.get('test_id')})")
                md.append(f"- **Severity:** `{b_item.get('issue_severity')}` | **Confidence:** `{b_item.get('issue_confidence')}`")
                md.append(f"- **Line Number:** {b_item.get('line_number')}")
                md.append(f"- **Issue Text:** {b_item.get('issue_text')}")
                md.append(f"```python\n{b_item.get('code')}\n```")
                md.append("\n")

        md.append("\n---\n")
        md.append("## ⚠️ Methodology & Security Limitations Statement")
        md.append("1. **Static Analysis Scope:** This audit report is generated using rule-based static Abstract Syntax Tree (AST) analysis and regex pattern matching.")
        md.append("2. **False Positives/Negatives:** Findings represent potential security weaknesses. Static analysis cannot guarantee detection of complex runtime logic errors, or prove exploitability without manual verification.")
        md.append("3. **Ethical & Educational Use:** This security review tool is designed exclusively for defensive educational security code reviews and developer guidance.")
        md.append("\n*Report generated by CodeAlpha Secure Coding Review & Analysis Suite.*")

        return "\n".join(md)

    @staticmethod
    def generate_json(analysis_results: Dict[str, Any]) -> str:
        return json.dumps(analysis_results, indent=2)
